# Generated by Django 3.1.4 on 2020-12-15 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=200)),
                ('country', models.EmailField(blank=True, max_length=200)),
                ('avatar', models.ImageField(default='avatarT.png', upload_to='avatars/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('link', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
